apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
data:
  uploads.ini: |-
    file_uploads = On
    memory_limit = 256M
    upload_max_filesize = 256M
    post_max_size = 256M
    max_execution_time = 600
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
        # ==============================================
        - image: wordpress
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_PASSWORD
              value: { { mysql_root_password } }
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            - name: uploads-ini
              mountPath: /usr/local/etc/php/conf.d/uploads.ini
              subPath: uploads.ini
        # ==============================================
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: { { mysql_root_password } }
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
        # ==============================================
      volumes:
        - name: mysql-persistent-storage
          nfs:
            server: { { nfs_server_ip } }
            path: { { volume_path } }
        - name: uploads-ini
          ConfigMap:
            name: wordpress-configmap
            defaultMode: 420
