apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <cert-name>
  namespace: default
spec:
  secretName: <secret-name>
  duration: 2160h # 80d
  renewBefore: 360h # 13h
  subject:
    organizations:
      - morgan-thibert-com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - <dns-name>
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
    group: cert-manager.io
